/**
 * Generate the reference docs that must never drift from the code:
 *
 *   docs/api/ENDPOINTS.md   every endpoint, from the contract
 *   docs/database/TABLES.md every table and column, from the Prisma schema
 *
 *   npm run docs -w backend
 *
 * CI can run this and fail on a diff; hand-written docs link here instead of
 * copying tables that would go stale.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { api, flattenApi, REALTIME_EVENTS, type Endpoint } from "@chs/contract";
import { z } from "zod";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const GENERATED = "<!-- Generated by backend/src/scripts/gen-docs.ts — do not edit by hand; run `npm run docs -w backend`. -->";

// ─── Endpoints ──────────────────────────────────────────────────────────────

function fields(schema: z.ZodType | undefined): string {
  if (!schema) return "—";
  try {
    const js = z.toJSONSchema(schema, { io: "input", unrepresentable: "any" }) as { properties?: Record<string, { type?: string | string[]; enum?: unknown[] }>; required?: string[] };
    const props = js.properties ?? {};
    const names = Object.keys(props);
    if (!names.length) return "—";
    return names
      .map((n) => {
        const p = props[n]!;
        const type = p.enum ? p.enum.map(String).join("\\|") : Array.isArray(p.type) ? p.type.join("\\|") : (p.type ?? "object");
        return `\`${n}${js.required?.includes(n) ? "" : "?"}\`: ${type}`;
      })
      .join("<br>");
  } catch {
    return "(see contract)";
  }
}

function access(e: Endpoint): string {
  const a = e.access;
  if (a.kind !== "society") return a.kind;
  if (!a.permission) return "any member";
  return ([] as string[]).concat(a.permission as string | string[]).map((p) => `\`${p}\``).join(" or ");
}

function endpointsDoc(): string {
  const all = flattenApi(api as never);
  const groups = new Map<string, Endpoint[]>();
  for (const e of all) groups.set(e.id.split(".")[0]!, [...(groups.get(e.id.split(".")[0]!) ?? []), e]);
  const out: string[] = [
    "# API endpoints",
    "",
    GENERATED,
    "",
    `${all.length} endpoints, base path \`/api/v1\`. Conventions (envelope, errors, pagination, idempotency, auth): [../API.md](../API.md). Source of truth: [packages/contract/src/endpoints](../../packages/contract/src/endpoints).`,
    "",
    "Access: `public` needs no token; `authenticated` needs any signed-in user; `platform` needs a platform admin; otherwise the caller must be an active member of the society in the path holding one of the listed permissions. Surface `gate`/`common` endpoints are the only ones a GUARD may call.",
    "",
    "## Contents",
    "",
    ...[...groups.keys()].map((g) => `- [${g}](#${g}) (${groups.get(g)!.length})`),
    "",
  ];
  for (const [g, list] of groups) {
    out.push(`## ${g}`, "", "| Id | Method & path | Access | Summary |", "|---|---|---|---|");
    for (const e of list) {
      const flags = [e.surface ? `surface: ${e.surface}` : null, e.idempotent ? "idempotent" : null, e.rateLimit ? `rate limit: ${e.rateLimit}` : null, e.allowRestricted ? "restricted token ok" : null].filter(Boolean).join(", ");
      out.push(`| \`${e.id}\` | \`${e.method} ${e.path}\` | ${access(e)}${flags ? `<br><sub>${flags}</sub>` : ""} | ${e.summary} |`);
    }
    out.push("");
    for (const e of list) {
      if (!e.query && !e.body && !e.invalidates?.length) continue;
      out.push(`<details><summary><code>${e.id}</code> — inputs and cache effects</summary>`, "");
      if (e.query) out.push(`**Query:** ${fields(e.query)}`, "");
      if (e.body) out.push(`**Body:** ${fields(e.body)}`, "");
      if (e.invalidates?.length) out.push(`**Invalidates:** ${e.invalidates.map((i) => `\`${i}\``).join(", ")}`, "");
      out.push("</details>", "");
    }
  }
  out.push("## Realtime events", "", "Pushed over Socket.io at `/realtime`; each refetches the reads it names. See [../server/REALTIME.md](../server/REALTIME.md).", "", "| Event | Invalidates |", "|---|---|");
  for (const [name, def] of Object.entries(REALTIME_EVENTS)) out.push(`| \`${name}\` | ${def.invalidates.map((i) => `\`${i}\``).join(", ")} |`);
  out.push("");
  return out.join("\n");
}

// ─── Tables ─────────────────────────────────────────────────────────────────

interface Model {
  name: string;
  table: string;
  doc: string[];
  fields: { name: string; column: string; type: string; attrs: string; doc: string }[];
  file: string;
}

function parseSchema(): { models: Model[]; enums: { name: string; values: string[] }[] } {
  const dir = join(root, "backend/prisma/schema");
  const enumNames = new Set(
    readdirSync(dir)
      .filter((f) => f.endsWith(".prisma"))
      .flatMap((f) => [...readFileSync(join(dir, f), "utf8").matchAll(/^enum (\w+) \{/gm)].map((m) => m[1]!)),
  );
  const models: Model[] = [];
  const enums: { name: string; values: string[] }[] = [];
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".prisma")).sort()) {
    const lines = readFileSync(join(dir, file), "utf8").split("\n");
    let pendingDoc: string[] = [];
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]!.trim();
      if (line.startsWith("///")) {
        pendingDoc.push(line.slice(3).trim());
        continue;
      }
      const m = /^model (\w+) \{/.exec(line);
      const en = /^enum (\w+) \{/.exec(line);
      if (en) {
        const values: string[] = [];
        while (!lines[++i]!.trim().startsWith("}")) {
          const v = lines[i]!.trim();
          if (v && !v.startsWith("//")) values.push(v);
        }
        enums.push({ name: en[1]!, values });
        pendingDoc = [];
        continue;
      }
      if (!m) {
        if (line && !line.startsWith("//")) pendingDoc = [];
        continue;
      }
      const model: Model = { name: m[1]!, table: m[1]!, doc: pendingDoc, fields: [], file };
      pendingDoc = [];
      let fieldDoc = "";
      while (!lines[++i]!.trim().startsWith("}")) {
        const f = lines[i]!.trim();
        if (f.startsWith("///")) {
          fieldDoc = f.slice(3).trim();
          continue;
        }
        const map = /@@map\("(\w+)"\)/.exec(f);
        if (map) model.table = map[1]!;
        const fm = /^(\w+)\s+([\w[\]?]+)\s*(.*)$/.exec(f);
        if (!fm || f.startsWith("@@") || f.startsWith("//")) continue;
        const [, name, type, attrs] = fm;
        // Relation fields (types that are other models) aren't columns.
        const base = type!.replace(/[[\]?]/g, "");
        const isRelation = !enumNames.has(base) && /^[A-Z]/.test(type!.replace(/[[\]?]/g, "")) && !/@db\.|@map|@default|@id|@unique/.test(attrs!) && !["String", "Int", "Boolean", "DateTime", "BigInt", "Decimal", "Json"].includes(type!.replace(/[[\]?]/g, ""));
        if (isRelation && (attrs!.includes("@relation") || type!.endsWith("[]") || !attrs)) continue;
        const column = /@map\("(\w+)"\)/.exec(attrs!)?.[1] ?? name!;
        model.fields.push({ name: name!, column, type: type!, attrs: attrs!.replace(/@map\("\w+"\)\s*/, "").trim(), doc: fieldDoc });
        fieldDoc = "";
      }
      models.push(model);
    }
  }
  return { models, enums };
}

function tablesDoc(): string {
  const { models, enums } = parseSchema();
  const out: string[] = [
    "# Database tables",
    "",
    GENERATED,
    "",
    `${models.length} tables, ${enums.length} enums. Design, conventions and the constraints that live outside Prisma: [../DATABASE.md](../DATABASE.md). Source: [backend/prisma/schema](../../backend/prisma/schema).`,
    "",
  ];
  const byFile = new Map<string, Model[]>();
  for (const m of models) byFile.set(m.file, [...(byFile.get(m.file) ?? []), m]);
  for (const [file, list] of byFile) {
    out.push(`## ${file.replace(".prisma", "")}`, "");
    for (const m of list) {
      out.push(`### \`${m.table}\` (${m.name})`, "");
      if (m.doc.length) out.push(m.doc.join(" "), "");
      out.push("| Column | Type | Notes |", "|---|---|---|");
      for (const f of m.fields) out.push(`| \`${f.column}\` | ${f.type.replace("?", " (nullable)")} | ${[f.doc, f.attrs.replace(/\|/g, "\\|")].filter(Boolean).join(" — ")} |`);
      out.push("");
    }
  }
  out.push("## Enums", "", "| Enum | Values |", "|---|---|");
  for (const e of enums) out.push(`| \`${e.name}\` | ${e.values.join(", ")} |`);
  out.push("");
  return out.join("\n");
}

function write(rel: string, content: string) {
  const path = join(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`wrote ${rel}`);
}

write("docs/api/ENDPOINTS.md", endpointsDoc());
write("docs/database/TABLES.md", tablesDoc());
