import { z } from "zod";
import { endpoint } from "../define";
import * as B from "../schemas/billing";
import { IsoDate, Ok, Page } from "../schemas/common";
import { inSociety, sp } from "./_shared";

export const billing = {
  heads: endpoint({
    method: "GET",
    path: sp("/charge-heads"),
    summary: "Charge heads with their rate history",
    access: inSociety(["billing.generate", "billing.publish", "society.configure"]),
    response: z.array(B.ChargeHead),
  }),
  createHead: endpoint({
    method: "POST",
    path: sp("/charge-heads"),
    summary: "Add a charge head (category decides the allowed apportionment)",
    access: inSociety(["billing.generate", "society.configure"]),
    body: B.CreateChargeHeadBody,
    response: B.ChargeHead,
    invalidates: ["billing.heads"],
  }),
  updateHead: endpoint({
    method: "PATCH",
    path: sp("/charge-heads/:headId"),
    summary: "Rename, re-filter, reorder or retire a head",
    access: inSociety(["billing.generate", "society.configure"]),
    body: B.UpdateChargeHeadBody,
    response: B.ChargeHead,
    invalidates: ["billing.heads"],
  }),
  setRate: endpoint({
    method: "POST",
    path: sp("/charge-heads/:headId/rates"),
    summary: "Set a rate from a date — never back into a billed period",
    access: inSociety(["billing.generate", "society.configure"]),
    body: B.SetRateBody,
    response: B.ChargeHead,
    invalidates: ["billing.heads"],
  }),
  simulate: endpoint({
    method: "GET",
    path: sp("/charge-heads/:headId/simulate"),
    summary: "Who would be billed how much for this head",
    access: inSociety(["billing.generate", "society.configure"]),
    query: z.object({ asOf: IsoDate.optional() }),
    response: B.Simulation,
  }),
  unitCharges: endpoint({
    method: "GET",
    path: sp("/unit-charges"),
    summary: "Per-unit amounts for manual heads",
    access: inSociety(["billing.generate", "society.configure"]),
    query: z.object({ headId: z.uuid().optional(), unitId: z.uuid().optional() }),
    response: z.array(B.UnitCharge),
  }),
  createUnitCharge: endpoint({
    method: "POST",
    path: sp("/unit-charges"),
    summary: "Set a per-unit amount for a manual head",
    access: inSociety(["billing.generate", "society.configure"]),
    body: B.CreateUnitChargeBody,
    response: B.UnitCharge,
    invalidates: ["billing.unitCharges"],
  }),
  runs: endpoint({
    method: "GET",
    path: sp("/bill-runs"),
    summary: "Bill runs, newest period first",
    access: inSociety(["billing.generate", "billing.publish"]),
    response: z.array(B.BillRunSummary),
  }),
  createRun: endpoint({
    method: "POST",
    path: sp("/bill-runs"),
    summary: "Generate a draft run for a period and preview it",
    access: inSociety("billing.generate"),
    body: B.CreateBillRunBody,
    response: B.BillRunPreview,
    invalidates: ["billing.runs"],
  }),
  run: endpoint({
    method: "GET",
    path: sp("/bill-runs/:runId"),
    summary: "Run preview: totals by head and building, variances, exceptions",
    access: inSociety(["billing.generate", "billing.publish"]),
    response: B.BillRunPreview,
  }),
  recomputeRun: endpoint({
    method: "POST",
    path: sp("/bill-runs/:runId/recompute"),
    summary: "Recalculate a draft after changing rates or units",
    access: inSociety("billing.generate"),
    response: B.BillRunPreview,
    invalidates: ["billing.run", "billing.runs", "billing.bills"],
  }),
  publishRun: endpoint({
    method: "POST",
    path: sp("/bill-runs/:runId/publish"),
    summary: "Publish: number the bills, post the ledger, notify residents",
    access: inSociety("billing.publish"),
    idempotent: true,
    response: B.BillRunPreview,
    invalidates: ["billing.run", "billing.runs", "billing.bills", "billing.ledger", "billing.myDues", "billing.myBills", "reports.dashboard"],
  }),
  discardRun: endpoint({
    method: "POST",
    path: sp("/bill-runs/:runId/discard"),
    summary: "Throw away a draft run",
    access: inSociety("billing.generate"),
    response: Ok,
    invalidates: ["billing.runs", "billing.bills"],
  }),
  bills: endpoint({
    method: "GET",
    path: sp("/bills"),
    summary: "Bills",
    access: inSociety(["billing.generate", "billing.publish", "payments.record", "accounts.manage"]),
    query: B.BillListQuery,
    response: Page(B.Bill),
  }),
  bill: endpoint({
    method: "GET",
    path: sp("/bills/:billId"),
    summary: "One bill with its head-wise breakup and the basis of each line",
    access: inSociety(),
    surface: "resident",
    response: B.Bill,
  }),
  cancelBill: endpoint({
    method: "POST",
    path: sp("/bills/:billId/cancel"),
    summary: "Cancel an unpaid bill (reversed in the ledger; reissue after)",
    access: inSociety("billing.publish"),
    body: B.CancelBillBody,
    response: B.Bill,
    invalidates: ["billing.bills", "billing.bill", "billing.ledger", "billing.myDues", "billing.myBills"],
  }),
  adhocBills: endpoint({
    method: "POST",
    path: sp("/bills/adhoc"),
    summary: "Supplementary bill to one or more units (repair contribution, penalty, NOC fee…)",
    access: inSociety("billing.publish"),
    idempotent: true,
    body: B.AdhocBillBody,
    response: z.object({ created: z.number().int(), bills: z.array(B.Bill) }),
    invalidates: ["billing.bills", "billing.ledger", "billing.myDues", "billing.myBills"],
  }),
  ledger: endpoint({
    method: "GET",
    path: sp("/units/:unitId/ledger"),
    summary: "Unit ledger with running balance",
    access: inSociety(),
    surface: "resident",
    query: z.object({ from: IsoDate.optional(), to: IsoDate.optional() }),
    response: B.Ledger,
  }),
  creditNote: endpoint({
    method: "POST",
    path: sp("/units/:unitId/credit-notes"),
    summary: "Issue a credit note (waiver or correction, reason required)",
    access: inSociety("billing.publish"),
    body: B.CreditNoteBody,
    response: B.CreditNote,
    invalidates: ["billing.ledger", "billing.myDues", "billing.bills"],
  }),
  myDues: endpoint({
    method: "GET",
    path: sp("/my/dues"),
    summary: "Dues card for each of my units",
    access: inSociety(),
    surface: "resident",
    response: z.array(B.Dues),
  }),
  myBills: endpoint({
    method: "GET",
    path: sp("/my/bills"),
    summary: "My bills, newest first",
    access: inSociety(),
    surface: "resident",
    query: B.BillListQuery,
    response: Page(B.Bill),
  }),
};
