import { z } from "zod";
import { endpoint } from "../define";
import { Id, Ok, Page, ListQuery } from "../schemas/common";
import * as M from "../schemas/members";
import { inSociety, sp } from "./_shared";

export const members = {
  list: endpoint({
    method: "GET",
    path: sp("/members"),
    summary: "Member register",
    access: inSociety("members.manage"),
    query: M.MemberListQuery,
    response: Page(M.Membership),
  }),
  unitOverview: endpoint({
    method: "GET",
    path: sp("/units/:unitId/overview"),
    summary: "Unit 360: owners, occupancy, tenant, family, vehicles, history",
    access: inSociety(),
    surface: "common",
    response: M.UnitOverview,
  }),
  addMembership: endpoint({
    method: "POST",
    path: sp("/units/:unitId/memberships"),
    summary: "Admit an owner, co-owner or associate member",
    access: inSociety("members.manage"),
    body: M.AddMembershipBody,
    response: M.Membership,
    invalidates: ["members.list", "members.unitOverview", "structure.units"],
  }),
  ceaseMembership: endpoint({
    method: "POST",
    path: sp("/memberships/:membershipId/cease"),
    summary: "End a membership (sets a cessation date; nothing is deleted)",
    access: inSociety("members.manage"),
    body: M.CeaseMembershipBody,
    response: M.Membership,
    invalidates: ["members.list", "members.unitOverview", "structure.units"],
  }),
  setNominees: endpoint({
    method: "PUT",
    path: sp("/memberships/:membershipId/nominees"),
    summary: "Replace a member's nominees",
    access: inSociety(),
    body: M.SetNomineesBody,
    response: z.array(M.Nominee),
    invalidates: ["members.unitOverview"],
  }),
  setOccupancy: endpoint({
    method: "PUT",
    path: sp("/units/:unitId/occupancy"),
    summary: "Record the unit's occupancy from a date (drives non-occupancy charges)",
    access: inSociety("members.manage"),
    body: M.SetOccupancyBody,
    response: M.Occupancy,
    invalidates: ["members.unitOverview", "structure.units"],
  }),
  createTenancy: endpoint({
    method: "POST",
    path: sp("/units/:unitId/tenancies"),
    summary: "Record a tenancy (owner requests go to approval)",
    access: inSociety(),
    body: M.CreateTenancyBody,
    response: z.union([M.Tenancy, z.object({ approvalId: Id })]),
    invalidates: ["members.unitOverview", "members.approvals", "structure.units"],
  }),
  updateTenancy: endpoint({
    method: "PATCH",
    path: sp("/tenancies/:tenancyId"),
    summary: "Edit or extend a tenancy",
    access: inSociety("members.manage"),
    body: M.UpdateTenancyBody,
    response: M.Tenancy,
    invalidates: ["members.unitOverview"],
  }),
  endTenancy: endpoint({
    method: "POST",
    path: sp("/tenancies/:tenancyId/end"),
    summary: "End a tenancy and suspend the tenant's access",
    access: inSociety(),
    body: M.EndTenancyBody,
    response: M.Tenancy,
    invalidates: ["members.unitOverview", "structure.units", "users.list"],
  }),
  addFamily: endpoint({
    method: "POST",
    path: sp("/units/:unitId/family"),
    summary: "Add a family member (residents' requests go to approval)",
    access: inSociety(),
    surface: "resident",
    body: M.FamilyMemberInput,
    response: z.union([M.FamilyMember, z.object({ approvalId: Id })]),
    invalidates: ["members.unitOverview", "members.myHome", "members.approvals"],
  }),
  removeFamily: endpoint({
    method: "DELETE",
    path: sp("/family/:familyMemberId"),
    summary: "Remove a family member",
    access: inSociety(),
    surface: "resident",
    response: Ok,
    invalidates: ["members.unitOverview", "members.myHome"],
  }),
  vehicles: endpoint({
    method: "GET",
    path: sp("/vehicles"),
    summary: "Vehicle register; the gate looks plates up here",
    access: inSociety(["members.manage", "gate.operate", "gate.manage"]),
    surface: "gate",
    query: M.VehicleSearchQuery,
    response: Page(M.Vehicle),
  }),
  addVehicle: endpoint({
    method: "POST",
    path: sp("/units/:unitId/vehicles"),
    summary: "Register a vehicle (residents' requests go to approval)",
    access: inSociety(),
    surface: "resident",
    body: M.VehicleInput,
    response: z.union([M.Vehicle, z.object({ approvalId: Id })]),
    invalidates: ["members.unitOverview", "members.vehicles", "members.myHome", "members.approvals"],
  }),
  removeVehicle: endpoint({
    method: "DELETE",
    path: sp("/vehicles/:vehicleId"),
    summary: "Remove a vehicle",
    access: inSociety(),
    surface: "resident",
    response: Ok,
    invalidates: ["members.unitOverview", "members.vehicles", "members.myHome"],
  }),
  addPet: endpoint({
    method: "POST",
    path: sp("/units/:unitId/pets"),
    summary: "Register a pet (residents' requests go to approval)",
    access: inSociety(),
    surface: "resident",
    body: M.PetInput,
    response: z.union([M.Pet, z.object({ approvalId: Id })]),
    invalidates: ["members.unitOverview", "members.myHome", "members.approvals"],
  }),
  removePet: endpoint({
    method: "DELETE",
    path: sp("/pets/:petId"),
    summary: "Remove a pet",
    access: inSociety(),
    surface: "resident",
    response: Ok,
    invalidates: ["members.unitOverview", "members.myHome"],
  }),
  approvals: endpoint({
    method: "GET",
    path: sp("/approvals"),
    summary: "Approvals queue",
    access: inSociety("members.manage"),
    query: M.ApprovalListQuery,
    response: Page(M.Approval),
  }),
  decideApproval: endpoint({
    method: "POST",
    path: sp("/approvals/:approvalId/decide"),
    summary: "Approve or reject a resident request",
    access: inSociety("members.manage"),
    body: M.DecideApprovalBody,
    response: M.Approval,
    invalidates: ["members.approvals", "members.unitOverview", "members.myHome", "members.vehicles"],
  }),
  myHome: endpoint({
    method: "GET",
    path: sp("/my/home"),
    summary: "The caller's own unit: members, family, vehicles, pets, pending requests",
    access: inSociety(),
    surface: "resident",
    response: z.object({ units: z.array(M.UnitOverview), pendingApprovals: z.array(M.Approval), recentDecisions: z.array(M.Approval) }),
  }),
  reportCorrection: endpoint({
    method: "POST",
    path: sp("/my/corrections"),
    summary: "Report an incorrect detail; creates an admin task",
    access: inSociety(),
    surface: "resident",
    body: M.DataCorrectionBody,
    response: z.object({ approvalId: Id }),
    invalidates: ["members.myHome"],
  }),
  directory: endpoint({
    method: "GET",
    path: sp("/directory"),
    summary: "Resident directory (respects each person's visibility choice)",
    access: inSociety(),
    surface: "resident",
    query: ListQuery,
    response: Page(M.DirectoryEntry),
  }),
  directoryPreference: endpoint({
    method: "PUT",
    path: sp("/my/directory-preference"),
    summary: "Choose whether and how you appear in the directory",
    access: inSociety(),
    surface: "resident",
    body: M.DirectoryPreference,
    response: M.DirectoryPreference,
    invalidates: ["members.directory"],
  }),
};
