import { endpoint } from "../define";
import { Ok, Page } from "../schemas/common";
import * as P from "../schemas/payments";
import { inSociety, sp } from "./_shared";

export const payments = {
  start: endpoint({
    method: "POST",
    path: sp("/my/payments"),
    summary: "Start an online payment for a unit I pay for",
    access: inSociety(),
    surface: "resident",
    idempotent: true,
    body: P.StartPaymentBody,
    response: P.Checkout,
    invalidates: ["payments.mine"],
  }),
  completeDummyCheckout: endpoint({
    method: "POST",
    path: sp("/my/payments/:paymentId/dummy-checkout"),
    summary: "Dummy gateway only: finish the simulated checkout as success or failure",
    access: inSociety(),
    surface: "resident",
    body: P.DummyCheckoutBody,
    response: P.Payment,
    invalidates: ["payments.mine", "payments.get", "billing.myDues", "billing.myBills", "billing.bill", "billing.ledger"],
  }),
  cancelCheckout: endpoint({
    method: "POST",
    path: sp("/my/payments/:paymentId/cancel"),
    summary: "Abandon an unfinished online checkout",
    access: inSociety(),
    surface: "resident",
    response: P.Payment,
    invalidates: ["payments.mine", "payments.get"],
  }),
  mine: endpoint({
    method: "GET",
    path: sp("/my/payments"),
    summary: "My payments and receipts",
    access: inSociety(),
    surface: "resident",
    query: P.PaymentListQuery,
    response: Page(P.Payment),
  }),
  get: endpoint({ method: "GET", path: sp("/payments/:paymentId"), summary: "One payment", access: inSociety(), surface: "resident", response: P.Payment }),
  list: endpoint({
    method: "GET",
    path: sp("/payments"),
    summary: "All payments (collections desk)",
    access: inSociety(["payments.record", "accounts.manage", "billing.publish"]),
    query: P.PaymentListQuery,
    response: Page(P.Payment),
  }),
  record: endpoint({
    method: "POST",
    path: sp("/payments"),
    summary: "Record cash, cheque or bank transfer (cheques stay pending until cleared)",
    access: inSociety("payments.record"),
    idempotent: true,
    body: P.RecordPaymentBody,
    response: P.Payment,
    invalidates: ["payments.list", "billing.bills", "billing.ledger", "reports.dashboard"],
  }),
  chequeAction: endpoint({
    method: "POST",
    path: sp("/payments/:paymentId/cheque"),
    summary: "Mark a cheque cleared or bounced",
    access: inSociety("payments.record"),
    body: P.ChequeActionBody,
    response: P.Payment,
    invalidates: ["payments.list", "payments.get", "billing.bills", "billing.ledger", "reports.dashboard"],
  }),
  cancelReceipt: endpoint({
    method: "POST",
    path: sp("/payments/:paymentId/cancel"),
    summary: "Cancel a receipt: the payment is reversed, never deleted",
    access: inSociety("payments.record"),
    body: P.CancelReceiptBody,
    response: P.Payment,
    invalidates: ["payments.list", "payments.get", "billing.bills", "billing.ledger", "reports.dashboard"],
  }),
  webhook: endpoint({
    method: "POST",
    path: "/webhooks/payments/:gateway",
    summary: "Gateway callback (signed, idempotent by event id)",
    access: { kind: "public" },
    body: P.GatewayWebhookBody,
    response: Ok,
  }),
};
