import { z } from "zod";
import { defineApi, endpoint, type Access } from "./define";
import type { Permission } from "./permissions";
import * as A from "./schemas/auth";
import { Id, Ok, Page, ListQuery } from "./schemas/common";
import * as M from "./schemas/members";
import * as P from "./schemas/platform";
import * as S from "./schemas/society";
import * as T from "./schemas/structure";
import * as U from "./schemas/users";

/**
 * Every endpoint of the API, in one place.
 *
 * The backend binds a handler to each entry and gets validation, access
 * control, auditing context and the response envelope from the entry itself.
 * Clients derive their typed calls, React Query keys and cache invalidation
 * from the same entries. Adding an endpoint means adding it here first.
 *
 * Paths are relative to `/api/v1`.
 */

/** Society-scoped path, typed as a literal so path params stay inferable. */
const sp = <P extends string>(p: P): `/societies/:societyId${P}` => `/societies/:societyId${p}`;
const society = (permission?: Permission | readonly Permission[]): Access =>
  permission ? { kind: "society", permission } : { kind: "society" };

export const api = defineApi({
  health: {
    live: endpoint({ method: "GET", path: "/health", summary: "Liveness and dependency checks", access: { kind: "public" }, response: P.Health }),
  },

  auth: {
    lookup: endpoint({
      method: "POST",
      path: "/auth/lookup",
      summary: "Decide the next sign-in screen for a mobile number",
      access: { kind: "public" },
      rateLimit: "auth",
      body: A.LookupBody,
      response: A.LookupResult,
    }),
    activate: endpoint({
      method: "POST",
      path: "/auth/activate",
      summary: "First sign-in: create a password for an admin-added number",
      access: { kind: "public" },
      rateLimit: "auth",
      body: A.ActivateBody,
      response: A.LoginResult,
    }),
    login: endpoint({
      method: "POST",
      path: "/auth/login",
      summary: "Sign in with mobile and password",
      access: { kind: "public" },
      rateLimit: "auth",
      body: A.LoginBody,
      response: A.LoginResult,
    }),
    verifyTwoFactor: endpoint({
      method: "POST",
      path: "/auth/2fa/verify",
      summary: "Complete an admin sign-in with a TOTP code",
      access: { kind: "public" },
      rateLimit: "auth",
      body: A.TwoFactorVerifyBody,
      response: A.LoginResult,
    }),
    refresh: endpoint({
      method: "POST",
      path: "/auth/refresh",
      summary: "Rotate the refresh token and issue a new access token",
      access: { kind: "public" },
      rateLimit: "sensitive",
      body: A.RefreshBody,
      response: A.TokenPair,
    }),
    logout: endpoint({
      method: "POST",
      path: "/auth/logout",
      summary: "End this session",
      access: { kind: "authenticated" },
      allowRestricted: true,
      body: A.LogoutBody,
      response: Ok,
    }),
    forcedChange: endpoint({
      method: "POST",
      path: "/auth/forced-change",
      summary: "Replace a temporary password; returns a full session",
      access: { kind: "authenticated" },
      allowRestricted: true,
      rateLimit: "sensitive",
      body: A.ForcedChangeBody,
      response: A.LoginResult,
    }),
  },

  me: {
    get: endpoint({ method: "GET", path: "/me", summary: "The signed-in user and their societies", access: { kind: "authenticated" }, response: A.Me }),
    update: endpoint({
      method: "PATCH",
      path: "/me",
      summary: "Update own name, email or language",
      access: { kind: "authenticated" },
      body: A.UpdateMeBody,
      response: A.Me,
      invalidates: ["me.get"],
    }),
    changePassword: endpoint({
      method: "POST",
      path: "/me/password",
      summary: "Change password; every other session is signed out",
      access: { kind: "authenticated" },
      rateLimit: "sensitive",
      body: A.ChangePasswordBody,
      response: Ok,
      invalidates: ["me.sessions"],
    }),
    sessions: endpoint({ method: "GET", path: "/me/sessions", summary: "Own active sessions", access: { kind: "authenticated" }, response: z.array(A.Session) }),
    revokeSession: endpoint({
      method: "DELETE",
      path: "/me/sessions/:sessionId",
      summary: "Sign out one device",
      access: { kind: "authenticated" },
      response: Ok,
      invalidates: ["me.sessions"],
    }),
    logoutAll: endpoint({
      method: "POST",
      path: "/me/logout-all",
      summary: "Sign out every device, this one included",
      access: { kind: "authenticated" },
      response: Ok,
    }),
    twoFactorSetup: endpoint({
      method: "POST",
      path: "/me/2fa/setup",
      summary: "Start TOTP enrolment (admins)",
      access: { kind: "authenticated" },
      response: A.TwoFactorSetup,
    }),
    twoFactorEnable: endpoint({
      method: "POST",
      path: "/me/2fa/enable",
      summary: "Confirm TOTP enrolment with a code",
      access: { kind: "authenticated" },
      body: A.TwoFactorCodeBody,
      response: Ok,
      invalidates: ["me.get"],
    }),
    twoFactorDisable: endpoint({
      method: "POST",
      path: "/me/2fa/disable",
      summary: "Turn TOTP off (needs a current code)",
      access: { kind: "authenticated" },
      body: A.TwoFactorCodeBody,
      response: Ok,
      invalidates: ["me.get"],
    }),
  },

  users: {
    list: endpoint({
      method: "GET",
      path: sp("/users"),
      summary: "Users of this society",
      access: society("users.manage"),
      query: U.UserListQuery,
      response: Page(U.SocietyUser),
    }),
    get: endpoint({ method: "GET", path: sp("/users/:userId"), summary: "One user", access: society("users.manage"), response: U.SocietyUser }),
    create: endpoint({
      method: "POST",
      path: sp("/users"),
      summary: "Add a user by mobile number — the only way anyone gets in",
      access: society("users.manage"),
      idempotent: true,
      body: U.CreateUserBody,
      response: U.SocietyUser,
      invalidates: ["users.list", "society.onboarding"],
    }),
    update: endpoint({
      method: "PATCH",
      path: sp("/users/:userId"),
      summary: "Change a user's details, type or permissions",
      access: society("users.manage"),
      body: U.UpdateUserBody,
      response: U.SocietyUser,
      invalidates: ["users.list", "users.get"],
    }),
    issueTempPassword: endpoint({
      method: "POST",
      path: sp("/users/:userId/temp-password"),
      summary: "Generate a single-use temporary password (24 h)",
      access: society("users.manage"),
      rateLimit: "sensitive",
      // Deliberately not idempotent: a replay would have to store the plain
      // password to return it again. A retry simply issues a fresh one.
      response: U.TempPasswordIssued,
      invalidates: ["users.get", "users.authEvents"],
    }),
    unlock: endpoint({
      method: "POST",
      path: sp("/users/:userId/unlock"),
      summary: "Clear a failed-attempt lockout",
      access: society("users.manage"),
      response: U.SocietyUser,
      invalidates: ["users.list", "users.get", "users.authEvents"],
    }),
    suspend: endpoint({
      method: "POST",
      path: sp("/users/:userId/suspend"),
      summary: "Suspend access to this society and revoke sessions",
      access: society("users.manage"),
      body: U.SuspendBody,
      response: U.SocietyUser,
      invalidates: ["users.list", "users.get", "users.sessions"],
    }),
    reactivate: endpoint({
      method: "POST",
      path: sp("/users/:userId/reactivate"),
      summary: "Restore a suspended user",
      access: society("users.manage"),
      response: U.SocietyUser,
      invalidates: ["users.list", "users.get"],
    }),
    logoutAll: endpoint({
      method: "POST",
      path: sp("/users/:userId/logout-all"),
      summary: "Force sign-out on every device",
      access: society("users.manage"),
      response: Ok,
      invalidates: ["users.sessions"],
    }),
    sessions: endpoint({
      method: "GET",
      path: sp("/users/:userId/sessions"),
      summary: "A user's active sessions",
      access: society("users.manage"),
      response: z.array(A.Session),
    }),
    authEvents: endpoint({
      method: "GET",
      path: sp("/users/:userId/auth-events"),
      summary: "A user's sign-in history",
      access: society("users.manage"),
      query: ListQuery,
      response: Page(A.AuthEvent),
    }),
    import: endpoint({
      method: "POST",
      path: sp("/users/import"),
      summary: "Bulk add users from CSV/XLSX (name, mobile, unit, user_type); dry run first",
      access: society("users.manage"),
      body: U.ImportBody,
      response: U.ImportReport,
      invalidates: ["users.list"],
    }),
    templates: endpoint({
      method: "GET",
      path: sp("/permission-templates"),
      summary: "Permission templates",
      access: society("users.manage"),
      response: z.array(U.PermissionTemplate),
    }),
    upsertTemplate: endpoint({
      method: "PUT",
      path: sp("/permission-templates/:code"),
      summary: "Create or edit a permission template",
      access: society("users.manage"),
      body: U.UpsertPermissionTemplateBody,
      response: U.PermissionTemplate,
      invalidates: ["users.templates"],
    }),
  },

  society: {
    get: endpoint({ method: "GET", path: sp(""), summary: "Society profile", access: society(), response: S.Society }),
    update: endpoint({
      method: "PATCH",
      path: sp(""),
      summary: "Edit the society profile",
      access: society("society.configure"),
      body: S.UpdateSocietyBody,
      response: S.Society,
      invalidates: ["society.get", "society.onboarding", "me.get"],
    }),
    settings: endpoint({ method: "GET", path: sp("/settings"), summary: "Society settings", access: society(), response: S.SocietySettings }),
    updateSettings: endpoint({
      method: "PATCH",
      path: sp("/settings"),
      summary: "Change society settings",
      access: society("society.configure"),
      body: S.UpdateSocietySettingsBody,
      response: S.SocietySettings,
      invalidates: ["society.settings"],
    }),
    onboarding: endpoint({
      method: "GET",
      path: sp("/onboarding"),
      summary: "Setup checklist and go-live readiness",
      access: society("society.configure"),
      response: S.Onboarding,
    }),
    goLive: endpoint({
      method: "POST",
      path: sp("/go-live"),
      summary: "Move the society from draft to live",
      access: society("society.configure"),
      response: S.Society,
      invalidates: ["society.get", "society.onboarding"],
    }),
    billingConfig: endpoint({
      method: "GET",
      path: sp("/billing-config"),
      summary: "Billing configuration",
      access: society(["society.configure", "billing.generate"]),
      response: S.BillingConfig,
    }),
    updateBillingConfig: endpoint({
      method: "PUT",
      path: sp("/billing-config"),
      summary: "Change billing configuration (applies from the next unbilled period)",
      access: society("society.configure"),
      body: S.UpdateBillingConfigBody,
      response: S.BillingConfig,
      invalidates: ["society.billingConfig", "society.onboarding"],
    }),
    bankAccounts: endpoint({
      method: "GET",
      path: sp("/bank-accounts"),
      summary: "Bank accounts",
      access: society(["society.configure", "accounts.manage", "payments.record"]),
      response: z.array(S.BankAccount),
    }),
    createBankAccount: endpoint({
      method: "POST",
      path: sp("/bank-accounts"),
      summary: "Add a bank account",
      access: society("society.configure"),
      body: S.CreateBankAccountBody,
      response: S.BankAccount,
      invalidates: ["society.bankAccounts", "society.onboarding"],
    }),
    updateBankAccount: endpoint({
      method: "PATCH",
      path: sp("/bank-accounts/:accountId"),
      summary: "Edit a bank account",
      access: society("society.configure"),
      body: S.UpdateBankAccountBody,
      response: S.BankAccount,
      invalidates: ["society.bankAccounts"],
    }),
    statutoryConfig: endpoint({
      method: "GET",
      path: sp("/statutory-config"),
      summary: "Statutory parameters in force, with history",
      access: society(["compliance.manage", "society.configure", "billing.generate"]),
      query: z.object({ asOf: z.iso.date().optional() }),
      response: z.array(S.StatutoryConfigEntry),
    }),
    setStatutoryConfig: endpoint({
      method: "POST",
      path: sp("/statutory-config"),
      summary: "Add an effective-dated society override",
      access: society("compliance.manage"),
      body: S.SetStatutoryConfigBody,
      response: S.StatutoryConfigEntry,
      invalidates: ["society.statutoryConfig"],
    }),
    auditLogs: endpoint({
      method: "GET",
      path: sp("/audit-logs"),
      summary: "Audit log",
      access: society("audit.view"),
      query: P.AuditListQuery,
      response: Page(P.AuditLog),
    }),
  },

  structure: {
    buildings: endpoint({ method: "GET", path: sp("/buildings"), summary: "Buildings", access: society(), response: z.array(T.Building) }),
    createBuilding: endpoint({
      method: "POST",
      path: sp("/buildings"),
      summary: "Add a building",
      access: society("society.configure"),
      body: T.CreateBuildingBody,
      response: T.Building,
      invalidates: ["structure.buildings", "society.onboarding"],
    }),
    updateBuilding: endpoint({
      method: "PATCH",
      path: sp("/buildings/:buildingId"),
      summary: "Edit a building",
      access: society("society.configure"),
      body: T.UpdateBuildingBody,
      response: T.Building,
      invalidates: ["structure.buildings"],
    }),
    units: endpoint({
      method: "GET",
      path: sp("/units"),
      summary: "Units",
      access: society(["society.configure", "members.manage", "billing.generate", "gate.operate", "gate.manage"]),
      surface: "common",
      query: T.UnitListQuery,
      response: Page(T.Unit),
    }),
    createUnit: endpoint({
      method: "POST",
      path: sp("/units"),
      summary: "Add a unit",
      access: society("society.configure"),
      body: T.CreateUnitBody,
      response: T.Unit,
      invalidates: ["structure.units", "structure.buildings", "society.onboarding"],
    }),
    bulkCreateUnits: endpoint({
      method: "POST",
      path: sp("/units/bulk"),
      summary: "Lay out a building's units by floor and pattern",
      access: society("society.configure"),
      body: T.BulkCreateUnitsBody,
      response: T.BulkCreateUnitsResult,
      invalidates: ["structure.units", "structure.buildings", "society.onboarding"],
    }),
    updateUnit: endpoint({
      method: "PATCH",
      path: sp("/units/:unitId"),
      summary: "Edit a unit",
      access: society("society.configure"),
      body: T.UpdateUnitBody,
      response: T.Unit,
      invalidates: ["structure.units", "members.unitOverview"],
    }),
    importUnits: endpoint({
      method: "POST",
      path: sp("/units/import"),
      summary: "Import units from CSV/XLSX; dry run first",
      access: society("society.configure"),
      body: U.ImportBody,
      response: U.ImportReport,
      invalidates: ["structure.units", "structure.buildings", "society.onboarding"],
    }),
    parking: endpoint({
      method: "GET",
      path: sp("/parking-slots"),
      summary: "Parking slot register",
      access: society(["society.configure", "members.manage"]),
      response: z.array(T.ParkingSlot),
    }),
    createParkingSlot: endpoint({
      method: "POST",
      path: sp("/parking-slots"),
      summary: "Add a parking slot",
      access: society("society.configure"),
      body: T.CreateParkingSlotBody,
      response: T.ParkingSlot,
      invalidates: ["structure.parking"],
    }),
    allotParkingSlot: endpoint({
      method: "POST",
      path: sp("/parking-slots/:slotId/allot"),
      summary: "Allot a slot to a unit, or free it",
      access: society("members.manage"),
      body: T.AllotParkingBody,
      response: T.ParkingSlot,
      invalidates: ["structure.parking", "members.unitOverview"],
    }),
  },

  members: {
    list: endpoint({
      method: "GET",
      path: sp("/members"),
      summary: "Member register",
      access: society("members.manage"),
      query: M.MemberListQuery,
      response: Page(M.Membership),
    }),
    unitOverview: endpoint({
      method: "GET",
      path: sp("/units/:unitId/overview"),
      summary: "Unit 360: owners, occupancy, tenant, family, vehicles, history",
      access: society(),
      surface: "common",
      response: M.UnitOverview,
    }),
    addMembership: endpoint({
      method: "POST",
      path: sp("/units/:unitId/memberships"),
      summary: "Admit an owner, co-owner or associate member",
      access: society("members.manage"),
      body: M.AddMembershipBody,
      response: M.Membership,
      invalidates: ["members.list", "members.unitOverview", "structure.units"],
    }),
    ceaseMembership: endpoint({
      method: "POST",
      path: sp("/memberships/:membershipId/cease"),
      summary: "End a membership (sets a cessation date; nothing is deleted)",
      access: society("members.manage"),
      body: M.CeaseMembershipBody,
      response: M.Membership,
      invalidates: ["members.list", "members.unitOverview", "structure.units"],
    }),
    setNominees: endpoint({
      method: "PUT",
      path: sp("/memberships/:membershipId/nominees"),
      summary: "Replace a member's nominees",
      access: society(),
      body: M.SetNomineesBody,
      response: z.array(M.Nominee),
      invalidates: ["members.unitOverview"],
    }),
    setOccupancy: endpoint({
      method: "PUT",
      path: sp("/units/:unitId/occupancy"),
      summary: "Record the unit's occupancy from a date (drives non-occupancy charges)",
      access: society("members.manage"),
      body: M.SetOccupancyBody,
      response: M.Occupancy,
      invalidates: ["members.unitOverview", "structure.units"],
    }),
    createTenancy: endpoint({
      method: "POST",
      path: sp("/units/:unitId/tenancies"),
      summary: "Record a tenancy (owner requests go to approval)",
      access: society(),
      body: M.CreateTenancyBody,
      response: z.union([M.Tenancy, z.object({ approvalId: Id })]),
      invalidates: ["members.unitOverview", "members.approvals", "structure.units"],
    }),
    updateTenancy: endpoint({
      method: "PATCH",
      path: sp("/tenancies/:tenancyId"),
      summary: "Edit or extend a tenancy",
      access: society("members.manage"),
      body: M.UpdateTenancyBody,
      response: M.Tenancy,
      invalidates: ["members.unitOverview"],
    }),
    endTenancy: endpoint({
      method: "POST",
      path: sp("/tenancies/:tenancyId/end"),
      summary: "End a tenancy and suspend the tenant's access",
      access: society(),
      body: M.EndTenancyBody,
      response: M.Tenancy,
      invalidates: ["members.unitOverview", "structure.units", "users.list"],
    }),
    addFamily: endpoint({
      method: "POST",
      path: sp("/units/:unitId/family"),
      summary: "Add a family member (residents' requests go to approval)",
      access: society(),
      surface: "resident",
      body: M.FamilyMemberInput,
      response: z.union([M.FamilyMember, z.object({ approvalId: Id })]),
      invalidates: ["members.unitOverview", "members.myHome", "members.approvals"],
    }),
    removeFamily: endpoint({
      method: "DELETE",
      path: sp("/family/:familyMemberId"),
      summary: "Remove a family member",
      access: society(),
      surface: "resident",
      response: Ok,
      invalidates: ["members.unitOverview", "members.myHome"],
    }),
    vehicles: endpoint({
      method: "GET",
      path: sp("/vehicles"),
      summary: "Vehicle register; the gate looks plates up here",
      access: society(["members.manage", "gate.operate", "gate.manage"]),
      surface: "gate",
      query: M.VehicleSearchQuery,
      response: Page(M.Vehicle),
    }),
    addVehicle: endpoint({
      method: "POST",
      path: sp("/units/:unitId/vehicles"),
      summary: "Register a vehicle (residents' requests go to approval)",
      access: society(),
      surface: "resident",
      body: M.VehicleInput,
      response: z.union([M.Vehicle, z.object({ approvalId: Id })]),
      invalidates: ["members.unitOverview", "members.vehicles", "members.myHome", "members.approvals"],
    }),
    removeVehicle: endpoint({
      method: "DELETE",
      path: sp("/vehicles/:vehicleId"),
      summary: "Remove a vehicle",
      access: society(),
      surface: "resident",
      response: Ok,
      invalidates: ["members.unitOverview", "members.vehicles", "members.myHome"],
    }),
    addPet: endpoint({
      method: "POST",
      path: sp("/units/:unitId/pets"),
      summary: "Register a pet (residents' requests go to approval)",
      access: society(),
      surface: "resident",
      body: M.PetInput,
      response: z.union([M.Pet, z.object({ approvalId: Id })]),
      invalidates: ["members.unitOverview", "members.myHome", "members.approvals"],
    }),
    removePet: endpoint({
      method: "DELETE",
      path: sp("/pets/:petId"),
      summary: "Remove a pet",
      access: society(),
      surface: "resident",
      response: Ok,
      invalidates: ["members.unitOverview", "members.myHome"],
    }),
    approvals: endpoint({
      method: "GET",
      path: sp("/approvals"),
      summary: "Approvals queue",
      access: society("members.manage"),
      query: M.ApprovalListQuery,
      response: Page(M.Approval),
    }),
    decideApproval: endpoint({
      method: "POST",
      path: sp("/approvals/:approvalId/decide"),
      summary: "Approve or reject a resident request",
      access: society("members.manage"),
      body: M.DecideApprovalBody,
      response: M.Approval,
      invalidates: ["members.approvals", "members.unitOverview", "members.myHome", "members.vehicles"],
    }),
    myHome: endpoint({
      method: "GET",
      path: sp("/my/home"),
      summary: "The caller's own unit: members, family, vehicles, pets, pending requests",
      access: society(),
      surface: "resident",
      response: z.object({ units: z.array(M.UnitOverview), pendingApprovals: z.array(M.Approval), recentDecisions: z.array(M.Approval) }),
    }),
    reportCorrection: endpoint({
      method: "POST",
      path: sp("/my/corrections"),
      summary: "Report an incorrect detail; creates an admin task",
      access: society(),
      surface: "resident",
      body: M.DataCorrectionBody,
      response: z.object({ approvalId: Id }),
      invalidates: ["members.myHome"],
    }),
    directory: endpoint({
      method: "GET",
      path: sp("/directory"),
      summary: "Resident directory (respects each person's visibility choice)",
      access: society(),
      surface: "resident",
      query: ListQuery,
      response: Page(M.DirectoryEntry),
    }),
    directoryPreference: endpoint({
      method: "PUT",
      path: sp("/my/directory-preference"),
      summary: "Choose whether and how you appear in the directory",
      access: society(),
      surface: "resident",
      body: M.DirectoryPreference,
      response: M.DirectoryPreference,
      invalidates: ["members.directory"],
    }),
  },

  platform: {
    societies: endpoint({
      method: "GET",
      path: "/platform/societies",
      summary: "All societies on the platform",
      access: { kind: "platform" },
      query: ListQuery,
      response: Page(P.PlatformSociety),
    }),
    createSociety: endpoint({
      method: "POST",
      path: "/platform/societies",
      summary: "Onboard a society and provision its first admin",
      access: { kind: "platform" },
      body: P.CreateSocietyBody,
      response: P.PlatformSociety,
      invalidates: ["platform.societies"],
    }),
  },
});

export type Api = typeof api;
