import type { z } from "zod";
import type * as A from "./schemas/auth";
import type * as M from "./schemas/members";
import type * as P from "./schemas/platform";
import type * as S from "./schemas/society";
import type * as T from "./schemas/structure";
import type * as U from "./schemas/users";

/** Wire types, inferred from the schemas — never written by hand. */
export type TokenPair = z.infer<typeof A.TokenPair>;
export type Me = z.infer<typeof A.Me>;
export type SocietyMembership = z.infer<typeof A.Membership>;
export type LoginResult = z.infer<typeof A.LoginResult>;
export type LookupResult = z.infer<typeof A.LookupResult>;
export type Session = z.infer<typeof A.Session>;
export type AuthEvent = z.infer<typeof A.AuthEvent>;
export type SocietyUser = z.infer<typeof U.SocietyUser>;
export type AccountStatus = z.infer<typeof U.AccountStatus>;
export type PermissionTemplate = z.infer<typeof U.PermissionTemplate>;
export type ImportReport = z.infer<typeof U.ImportReport>;
export type Society = z.infer<typeof S.Society>;
export type SocietySettings = z.infer<typeof S.SocietySettings>;
export type Onboarding = z.infer<typeof S.Onboarding>;
export type BillingConfig = z.infer<typeof S.BillingConfig>;
export type BankAccount = z.infer<typeof S.BankAccount>;
export type StatutoryConfigEntry = z.infer<typeof S.StatutoryConfigEntry>;
export type Building = z.infer<typeof T.Building>;
export type Unit = z.infer<typeof T.Unit>;
export type ParkingSlot = z.infer<typeof T.ParkingSlot>;
export type MemberRecord = z.infer<typeof M.Membership>;
export type Occupancy = z.infer<typeof M.Occupancy>;
export type Tenancy = z.infer<typeof M.Tenancy>;
export type FamilyMember = z.infer<typeof M.FamilyMember>;
export type Vehicle = z.infer<typeof M.Vehicle>;
export type Pet = z.infer<typeof M.Pet>;
export type Nominee = z.infer<typeof M.Nominee>;
export type Approval = z.infer<typeof M.Approval>;
export type UnitOverview = z.infer<typeof M.UnitOverview>;
export type DirectoryEntry = z.infer<typeof M.DirectoryEntry>;
export type AuditLog = z.infer<typeof P.AuditLog>;
export type PlatformSociety = z.infer<typeof P.PlatformSociety>;
export type Health = z.infer<typeof P.Health>;
export type AppNotification = z.infer<typeof import("./schemas/notifications").Notification>;
export type NotificationPreferences = z.infer<typeof import("./schemas/notifications").NotificationPreferences>;
export type NoticeRecord = z.infer<typeof import("./schemas/notifications").Notice>;
export type Audience = z.infer<typeof import("./schemas/notifications").Audience>;
export type ChargeHead = z.infer<typeof import("./schemas/billing").ChargeHead>;
export type BillRecord = z.infer<typeof import("./schemas/billing").Bill>;
export type BillRunPreview = z.infer<typeof import("./schemas/billing").BillRunPreview>;
export type Dues = z.infer<typeof import("./schemas/billing").Dues>;
export type Ledger = z.infer<typeof import("./schemas/billing").Ledger>;
export type PaymentRecord = z.infer<typeof import("./schemas/payments").Payment>;
export type Checkout = z.infer<typeof import("./schemas/payments").Checkout>;
export type Dashboard = z.infer<typeof import("./schemas/reports").Dashboard>;
export type ReportData = z.infer<typeof import("./schemas/reports").ReportData>;
export type ChargeCategory = import("./schemas/billing").ChargeCategory;
export type ApportionmentMethod = import("./schemas/billing").ApportionmentMethod;
